stages:
  - test
  - deploy
services:
  - memcached:1.4

DjangoTest:
  image: python:3.6
  stage: test
  before_script:
    #Reference : Lab PPW Odd Semester 2017/2018
    - chmod +x ./setup-script.sh
    - ./setup-script.sh $GITLAB_USER_LOGIN
    - python manage.py collectstatic --no-input
    - python manage.py runserver 8000 &
  when: on_success
  script:
    - ./django-lint.sh
    - if [[ $GITLAB_USER_LOGIN == "faiz97" || $GITLAB_USER_LOGIN == "sarahdfxo" || $GITLAB_USER_LOGIN == "tinna.fauziah" ]]; then coverage run --include='api/*','mahasiswa/*' manage.py test api.tests_functional; fi
    - coverage run --include='api/*','mahasiswa/*' --omit='mahasiswa/utils.py','mahasiswa/views.py' --append manage.py test api.tests_unit api.db.tests_unit api.ml_models.tests_unit api.siak.tests_unit mahasiswa.tests_unit
    - coverage report -m --fail-under=90
  coverage: '/\d+\%\s*$/'

DeploymentProduction:
  image: ruby:2.4
  stage: deploy
  only: 
    - master
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=prima-pplc7 --api-key=$API_KEY
    - export HEROKU_API_KEY=$API_KEY
    - heroku run bash --app prima-pplc7 deployment.sh
  environment:
    name: production
    url: https://prima-pplc7.herokuapp.com/

DeploymentStaging:
  image: ruby:2.4
  stage: deploy
  only: 
    - sit_uat
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=prima-sit-uat --api-key=$API_KEY
    - export HEROKU_API_KEY=$API_KEY
    - heroku run bash --app prima-sit-uat deployment.sh 
  environment:
    name: staging
    url: https://prima-sit-uat.herokuapp.com/

DeploymentCobacoba:
  image: ruby:2.4
  stage: deploy
  except:
    - master 
    - sit_uat
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=prima-cobacoba --api-key=$API_KEY
    - export HEROKU_API_KEY=$API_KEY
    - heroku run bash --app prima-cobacoba deployment.sh
  environment:
    name: coba-coba
    url: https://prima-cobacoba.herokuapp.com/

